### ISSUE TITLE
Where XDebug actually stores the breakpoints when we pushed Ctrl+F8?

### ISSUE THREAD

**Issue by chelder86** [martomo/SublimeTextXdebug#125]
XDebug stops at a line but there is not any (visible) breakpoint there. I think there was a breakpoint there once but not anymore.

To remove it, I tried the following:

1) Put a breakpoint in that line to remove it right after.
2) Of course, I also pushed "Clear All Breakpoints". The debugger is still stopping in that line!

I guess must be some file somewhere where there is a sentence which tells Xdebug to stop in that line. I haven't been able to find that file yet. I tried to look for it in Auto Save Session.sublime_session and looking for some strings within my home folder using the grep command.

I'm on Ubuntu 14.04LTS. I'm on Sublime Text 3 build 3065. I installed XDebug through the package manager of Sublime.

**Comment by chelder86** [comment]
More stuff I have done. I have removed:

- ~/.config/sublime-text-3/Packages/User/Xdebug.breakpoints
- The .sublime-workspace file
- The Cache and Local folders from the ~/.config/sublime-text-3 folder

It's still stopping there!

**Comment by chelder86** [comment]
Now, it is failing to move the cursor and show information in the Xdebug Context. I mean, it does stop at the wrong place where there is not any (visible) breakpoint, and I can see the XDebug Context data and the cursor moving when I push Step Over or whatever.

However, it stops in the "real" breakpoint I put, but I can't see anything in the Xdebug Context. The cursor sticks at the same line when I push Step Over (though the screen moves down!).

**Comment by chelder86** [comment]
I pushed Ctrl+F6 (Step Over) several times. I got the following errors:

1) Please restart Xdebug debugging session. Disconnected from Xdebug debugger engine. 'NoneType' object has no attribute 'send'
2) Please restart Xdebug debugging session. Disconnected from Xdebug debugger engine. 'utf-8' codec can't decode byte 0xc3 in position 1023: unexpected end of data.

I have attached a screenshot with the error:

![xdebug error shown](https://cloud.githubusercontent.com/assets/3020189/5615287/4666d530-94fa-11e4-8b48-7ffd1703a830.png)

**Comment by UniFreak** [comment]
I got the same issue on win7 64bit, using sublime text 
can't find any thing searching google

here the log in console I think related to this:
Traceback (most recent call last):
  File "C:\Program Files\Sublimetext3\sublime_plugin.py", line 438, in is_enabled_
    ret = self.is_enabled(**args)
  File "phpunit in C:\Program Files\Sublimetext3\Data\Installed Packages\PHPUnit.sublime-package", line 1223, in is_enabled
  File "phpunit in C:\Program Files\Sublimetext3\Data\Installed Packages\PHPUnit.sublime-package", line 1230, in is_visible
  File "phpunit in C:\Program Files\Sublimetext3\Data\Installed Packages\PHPUnit.sublime-package", line 503, in is_phpunitxml
TypeError: argument of type 'NoneType' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublimetext3\sublime_plugin.py", line 442, in is_enabled_
    ret = self.is_enabled()
  File "phpunit in C:\Program Files\Sublimetext3\Data\Installed Packages\PHPUnit.sublime-package", line 1223, in is_enabled
  File "phpunit in C:\Program Files\Sublimetext3\Data\Installed Packages\PHPUnit.sublime-package", line 1230, in is_visible
  File "phpunit in C:\Program Files\Sublimetext3\Data\Installed Packages\PHPUnit.sublime-package", line 503, in is_phpunitxml
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Program Files\Sublimetext3\sublime_plugin.py", line 438, in is_enabled_
    ret = self.is_enabled(**args)
  File "phpunit in C:\Program Files\Sublimetext3\Data\Installed Packages\PHPUnit.sublime-package", line 1223, in is_enabled
  File "phpunit in C:\Program Files\Sublimetext3\Data\Installed Packages\PHPUnit.sublime-package", line 1230, in is_visible
  File "phpunit in C:\Program Files\Sublimetext3\Data\Installed Packages\PHPUnit.sublime-package", line 503, in is_phpunitxml
TypeError: argument of type 'NoneType' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublimetext3\sublime_plugin.py", line 442, in is_enabled_
    ret = self.is_enabled()
  File "phpunit in C:\Program Files\Sublimetext3\Data\Installed Packages\PHPUnit.sublime-package", line 1223, in is_enabled
  File "phpunit in C:\Program Files\Sublimetext3\Data\Installed Packages\PHPUnit.sublime-package", line 1230, in is_visible
  File "phpunit in C:\Program Files\Sublimetext3\Data\Installed Packages\PHPUnit.sublime-package", line 503, in is_phpunitxml
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Program Files\Sublimetext3\sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "phpunit in C:\Program Files\Sublimetext3\Data\Installed Packages\PHPUnit.sublime-package", line 1230, in is_visible
  File "phpunit in C:\Program Files\Sublimetext3\Data\Installed Packages\PHPUnit.sublime-package", line 503, in is_phpunitxml
TypeError: argument of type 'NoneType' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublimetext3\sublime_plugin.py", line 460, in is_visible_
    ret = self.is_visible()
  File "phpunit in C:\Program Files\Sublimetext3\Data\Installed Packages\PHPUnit.sublime-package", line 1230, in is_visible
  File "phpunit in C:\Program Files\Sublimetext3\Data\Installed Packages\PHPUnit.sublime-package", line 503, in is_phpunitxml
TypeError: argument of type 'NoneType' is not iterable
error: Please restart Xdebug debugging session.
Disconnected from Xdebug debugger engine.
[WinError 10054] 远程主机强迫关闭了一个现有的连接。
error: Please restart Xdebug debugging session.
Disconnected from Xdebug debugger engine.
'NoneType' object has no attribute 'send'

**Comment by thomasandersen** [comment]
I may be late to the conversation here, but check the last entry in the Xdebug Stack tab. Does it say a PHP error?

By default, SublimeTextXdebug breaks on exceptions (see break_on_exception)
In OP's case, I guess there is a PHP Notice error (hint: $settings). Fix the problem code and the debugger will continue to the next break point. Last option should be to override break_on_exception.

**Comment by kalecgos0616** [comment]
try to clear all Xdebug Watch
