### ISSUE TITLE
Xdebug fails to move the cursor when debugging and shows the XDebug Context empty

### ISSUE THREAD

**Issue by chelder86** [martomo/SublimeTextXdebug#126]
The pointer stops in the breakpoint I put with Ctrl+F8, but I can't see anything in the Xdebug Context. The cursor sticks at the same line when I push Step Over (though the screen moves down!).

Notice that the pointer does stop in the other place where there is not any (visible) breakpoint, and I can see the XDebug Context data and the cursor moving when I push Step Over. That's why this bug seems related to the previous posted issue [XDebug stops at a line without (visible) breakpoint]: https://github.com/martomo/SublimeTextXdebug/issues/125

**Comment by chelder86** [comment]
I pushed Ctrl+F6 (Step Over) several times. I got the following errors:

1) Please restart Xdebug debugging session. Disconnected from Xdebug debugger engine. 'NoneType' object has no attribute 'send'
2) Please restart Xdebug debugging session. Disconnected from Xdebug debugger engine. 'utf-8' codec can't decode byte 0xc3 in position 1023: unexpected end of data.

I have attached a screenshot with the error:

![xdebug error shown](https://cloud.githubusercontent.com/assets/3020189/5615287/4666d530-94fa-11e4-8b48-7ffd1703a830.png)

**Comment by marcules** [comment]
@chelder86 did you ever find out what caused this?  
I have the same issue in my windows environment - it stopped working suddenly - , where it stops on a (visible) breakpoint, and I see the data being sent from the server, but the context and stack remain empty.

**Comment by Ralle** [comment]
![skaermbillede 2015-05-26 07 09 17](https://cloud.githubusercontent.com/assets/467309/7805756/57f7dd20-0378-11e5-9329-d2445e947d2d.png)
Also happens on Windows with Xdebug on Linux.

**Comment by webIMT** [comment]
I have too the same issue... on OS X Yosemite.
![capture d ecran 2015-06-05 a 16 23 13](https://cloud.githubusercontent.com/assets/2249572/8007929/3ba15a78-0b9f-11e5-9e2c-0824b4300134.png)

Could you help us fix it ?

**Comment by jtl999** [comment]
Same issue. OSX 10.11.

Is an OS independent bug and has to deal with handling of Unicode.

Anyone have any advice?

**Comment by jtl999** [comment]
````
Exception in thread Thread-47:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "./xdebug/session.py", line 148, in run
  File "./xdebug/session.py", line 242, in execute
  File "./xdebug/session.py", line 274, in get_context_values
  File "./xdebug/protocol.py", line 185, in read
  File "./xdebug/protocol.py", line 137, in unescape
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/re.py", line 151, in sub
    return _compile(pattern, 0).sub(repl, string, count)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 85: ordinal not in range(128)

````
