### ISSUE TITLE
"max_depth" more than 2 cause xml.etree.ElementTree.ParseError

### ISSUE THREAD

**Issue by ccyeh0901** [martomo/SublimeTextXdebug#156]
Hello, 
I've reviewed the #77 issue and updated the python code but no work. the same message show in console only when I set the max_depth more than 2 ( ex: 3, 4, 5....), when max_depth is lower than 2, everything is ok. That means I can't inspect the variables more than second level (help......)

below are the info of my environment:
console error message shown:

Exception in thread Thread-519:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/Users/ccyeh0901/Library/Application Support/Sublime Text 3/Packages/SublimeTextXdebug-master/xdebug/session.py", line 148, in run
    self.execute(self.get_option('command'))
  File "/Users/ccyeh0901/Library/Application Support/Sublime Text 3/Packages/SublimeTextXdebug-master/xdebug/session.py", line 242, in execute
    context = self.get_context_values()
  File "/Users/ccyeh0901/Library/Application Support/Sublime Text 3/Packages/SublimeTextXdebug-master/xdebug/session.py", line 279, in get_context_values
    response = S.SESSION.read()
  File "/Users/ccyeh0901/Library/Application Support/Sublime Text 3/Packages/SublimeTextXdebug-master/xdebug/protocol.py", line 191, in read
    document = ET.fromstring(data)
  File "./xml/etree/ElementTree.py", line 1356, in XML
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 2, column 173624

=====
Xdebug.sublime.-settings

    "url": "http://localhost/",
    "launch_browser": true,
    "max_children": 256,
    "port": 9001,
    "max_data": 4096,
    "max_depth": 3,
    "close_on_stop": true,
    "pretty_output": true,
    "disable_layout": true,
    "debug": false,
====

[xdebug]
zend_extension="/Applications/MAMP/bin/php/php5.6.10/lib/php/extensions/no-debug-non-zts-20131226/xdebug.so"
xdebug.remote_enable = 1
xdebug.remote_host=127.0.0.1
xdebug.remote_port = 9001
xdebug.remote_handler = "dbgp"
xdebug.remote_log = "/var/log/xdebug/xdebug.log"

OS: OSX EI Captain
sublime text 3
=====

I've google a lot, but no solution. Really appreciate this plugin which makes programer work faster. Please give me a hand to solve this bug.
Thanks a ton.

**Comment by slifin** [comment]
Can also confirm this bug on ubuntu ST3

**Comment by petervansark** [comment]
I have the same issue on ST3 Windows

**Comment by holt83** [comment]
I'm experiencing this problem too on ST3 - both on Windows and Ubuntu. I'm fairly certain it has something to do with character encoding. 

Just tested with a variable and as soon as I removed the character 'å' from the variable I could see the context again with max_depth > 2.

**Comment by Vicilu** [comment]
It's 2018 and this is still a problem

**Comment by mercurykd** [comment]
When I set max_depth> 10, xdebug (server) to the command context_get -c 0 is just silent, apparently this is not a plug-in fault.

**Comment by mercurykd** [comment]
https://bugs.xdebug.org/view.php?id=1569
