### ISSUE TITLE
Xdebug Context tab doesn't show anything after commit 4324974

### ISSUE THREAD

**Issue by paulodiovani** [martomo/SublimeTextXdebug#78]
After commit 4324974 the Context tab (current variables) stopped working on Sublime Text 3, with the folowing errors:

```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "/home/paulo.goncalves/.config/sublime-text-3/Packages/Xdebug Client/xdebug/session.py", line 148, in run
    self.execute(self.get_option('command'))
  File "/home/paulo.goncalves/.config/sublime-text-3/Packages/Xdebug Client/xdebug/session.py", line 242, in execute
    context = self.get_context_values()
  File "/home/paulo.goncalves/.config/sublime-text-3/Packages/Xdebug Client/xdebug/session.py", line 274, in get_context_values
    response = S.SESSION.read()
  File "/home/paulo.goncalves/.config/sublime-text-3/Packages/Xdebug Client/xdebug/protocol.py", line 161, in read
    document = ET.fromstring(data)
  File "X/xml/etree/ElementTree.py", line 1356, in XML
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 2, column 92259
```

By checking out the previous commit the error doesn't work.

**Comment by EwingYangs** [comment]
I encountered the same problem. I changed the version of xdebug.so from 2.6.0 to 2.5.0, and the problem was solved
