### ISSUE TITLE
Xdebug can't parse xml response

### ISSUE THREAD

**Issue by HoffmannP** [martomo/SublimeTextXdebug#80]
I'm getting an exception that might be connected to #78:

```
Exception in thread Thread-510:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File "./xdebug/session.py", line 151, in run
  File "./xdebug/session.py", line 335, in init
  File "./xdebug/protocol.py", line 188, in read
  File "<string>", line 84, in XML
RuntimeError: cannot load dispatch table from pyexpat
```

**Comment by FatBoyXPC** [comment]
@martomo I'm still having the same issues as the @HoffmannP. I'm having trouble finding a python2.6 with a lib-dynload directory that has pyexpat.so. The strange thing is, /usr/lib/python2.7/lib-dynload/pyexpat.x86_64-linux-gnu.so exists.

Ubuntu 14.04
>>> sys.version_info
(2, 6, 6, 'final', 0)
Installed Xdebug Client via package control
Xdebug Version: 2.2.3
Running script through browser
xdebug config same as above
xdebug settings in sublime are default, with the url mapping ot my project's url.

Error: 
Exception in thread Thread-26:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File "./xdebug/session.py", line 151, in run
  File "./xdebug/session.py", line 335, in init
  File "./xdebug/protocol.py", line 191, in read
  File "<string>", line 84, in XML
RuntimeError: cannot load dispatch table from pyexpat

**Comment by RustJason** [comment]
@FatBoyXPC  Did you fixed it ? I have the same problem.

**Comment by FatBoyXPC** [comment]
@RustJason I just ended up using ST3 :P

**Comment by RustJason** [comment]
@FatBoyXPC  Thanks.
